Traceback (most recent call last):
  File "./mmdetection/tools/test.py", line 7, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'
Traceback (most recent call last):
  File "./mmdetection/tools/test.py", line 7, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', './mmdetection/tools/test.py', '--local_rank=7', 'mmdetection/configs/adaptive/faster_rcnn_r50_caffe_fpn_mstrain_1x_coco-person_adaptive.py', '/root/WORK_DIRS/GPA/tuning/coco_piropo_100a_da_rcnn01_intra_inter0_cosine_divd_nostep_iter/latest.pth', '--launcher', 'pytorch', '--eval', 'bbox', '--cfg-options', 'data.samples_per_gpu=2', 'data.test.ann_file=/data/PIROPO/omni_test2.json', 'data.test.img_prefix=None', '--out', '/root/WORK_DIRS/GPA/tuning/coco_piropo_100a_da_rcnn01_intra_inter0_cosine_divd_nostep_iter/piropo_test2.pkl']' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "./mmdetection/tools/test.py", line 7, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'
Traceback (most recent call last):
  File "./mmdetection/tools/test.py", line 7, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'
Traceback (most recent call last):
  File "./mmdetection/tools/test.py", line 7, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'
Traceback (most recent call last):
  File "./mmdetection/tools/test.py", line 7, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'
Traceback (most recent call last):
  File "./mmdetection/tools/test.py", line 7, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'
Traceback (most recent call last):
  File "./mmdetection/tools/test.py", line 7, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'
